### ISSUE TITLE
Need a detailed tutorial on how to use it, thanks

### ISSUE THREAD

**Issue by crimes2** [Gabriellgpc/pexel-downloader#1]
The first time I used python, I tried to manipulate it, but it didn't work.

**Comment by Gabriellgpc** [comment]
Ty for noticed the repo.
Sure, I was really planning to make a simples step-by-step guide of how to
use it. Keep watching the repo, please, the next updates will have more
detailed of how to use it then.

**Comment by Gabriellgpc** [comment]
@crimes2 hope it will help you to start using it.
https://medium.com/@condadoslgpc/how-to-automatically-download-open-license-images-using-python-and-pexel-downloader-10291ebd0cd3
